### PR TITLE
Make the About window unminimizable

### PR DESCRIPTION
**Pull request by sindresorhus**
About windows on macOS are usually not minimizable.

<h3 align="center">Before & After</h1>

<div align="left"></div><div align="left"></div>

### CODE REVIEW

**Comment by leo** [comment]
Thanks! 😊 We had a few problems with babel dependencies though (which caused the tests to fail). So please update the branch and everything should work fine!

**Comment by sindresorhus** [comment]
Done

**Comment by leo** [comment]
Whoops...

Also forgot that it's now possible to do "rebase merging". Will do that next time! Thanks though! ❤️

**Comment by sindresorhus** [comment]
@leo IMHO, usually better to do squashing regardless. Cleaner commit history. And in this case, I had a useless merge commit, as I used the `Update` here instead of rebasing locally, since I'm lazy. I think rebase merging would have brought with it that commit.

**Comment by leo** [comment]
@sindresorhus Ah, thanks for the tip!

**Pull request merged**
